if(VAR [VAR] != 30)
if(VAR  == 30)
if(VAR  == NULL)
if(VAR  != VAR)
if(VAR  >= NULL)
if(VAR [VAR] >= NULL)
if(VAR  >= NULL)
if(VAR  == VAR)
if(VAR [VAR] >= 10)
if(VAR  == 40)
if(VAR  <= 10)
if(VAR [VAR] <= 20)
if(VAR [VAR] == 30)
if(VAR [VAR] >= 10)
if(VAR  != 10)
if(VAR  <= 30)
if(VAR [VAR] != 10)
if(VAR  != 30)
if(VAR  <= 10)
if(VAR  == 40)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= 40)
if(VAR  <= 40)
if(VAR [VAR] == 10)
if(VAR  != VAR)
if(VAR [VAR] <= 40)
if(VAR  != NULL)
if(VAR [VAR] != 40)
if(VAR [VAR] >= 30)
if(VAR [VAR] != 20)
if(VAR  == NULL)
if(VAR [VAR] != 40)
if(VAR [VAR] >= 30)
if(VAR  != 40)
if(VAR  >= 40)
if(VAR [VAR] != 40)
if(VAR [VAR] == 10)
if(VAR  != 40)
if(VAR  >= 40)
if(VAR [VAR] != 10)
if(VAR  == 20)
if(VAR [VAR] == 20)
if(VAR  == 10)
if(VAR  != 10)
if(VAR [VAR] <= VAR)
if(VAR [VAR] == NULL)
if(VAR  <= 40)
if(VAR [VAR] == 20)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == 40)
if(VAR [VAR] == 30)
if(VAR [VAR] == 20)
if(VAR  == 40)
if(VAR  >= 20)
if(VAR  == VAR)
if(VAR [VAR] == VAR)
if(VAR  != 30)
if(VAR [VAR] == 40)
if(VAR  != 30)
if(VAR  != 30)
if(VAR  != NULL)
if(VAR [VAR] <= NULL)
if(VAR  <= 30)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == VAR)
if(VAR  == 30)
if(VAR [VAR] == 10)
if(VAR  == 40)
if(VAR  == 40)
if(VAR  <= 40)
if(VAR  <= VAR)
if(VAR [VAR] == NULL)
if(VAR [VAR] <= 30)
if(VAR  == 30)
if(VAR [VAR] <= NULL)
if(VAR  != 10)
if(VAR [VAR] >= 10)
if(VAR  == VAR)
if(VAR  != 40)
if(VAR  >= 30)
if(VAR  <= VAR)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 30)
if(VAR  == 30)
if(VAR  <= 20)
if(VAR  != 30)
if(VAR [VAR] != 30)
if(VAR  >= VAR)
if(VAR  == 20)
if(VAR  >= 30)
if(VAR [VAR] == VAR)
if(VAR  >= NULL)
if(VAR [VAR] <= NULL)
if(VAR  != 40)
if(VAR  != NULL)
if(VAR  == 20)
if(VAR [VAR] != 40)
if(VAR [VAR] != 10)
if(VAR  != 30)
if(VAR [VAR] <= 30)
if(VAR  <= 30)
if(VAR [VAR] <= 10)
if(VAR  != 30)
if(VAR [VAR] <= 10)
if(VAR [VAR] == 40)
if(VAR [VAR] <= 40)
if(VAR [VAR] <= 30)
if(VAR  >= 10)
if(VAR [VAR] == VAR)
if(VAR  != VAR)
if(VAR  != VAR)
if(VAR [VAR] == 10)
if(VAR  <= VAR)
if(VAR [VAR] != 20)
if(VAR  >= VAR)
if(VAR  == 40)
if(VAR [VAR] <= 20)
if(VAR  == 30)
if(VAR  >= 10)
if(VAR [VAR] != NULL)
if(VAR  == 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == 30)
if(VAR  != 40)
if(VAR [VAR] <= 20)
if(VAR  >= 40)
if(VAR [VAR] == VAR)
if(VAR [VAR] != 30)
if(VAR [VAR] <= NULL)
if(VAR  == NULL)
if(VAR  <= 30)
if(VAR [VAR] >= VAR)
if(VAR  == 10)
if(VAR [VAR] == 10)
if(VAR [VAR] != NULL)
if(VAR  == NULL)
if(VAR  == 10)
if(VAR [VAR] >= 40)
if(VAR  != VAR)
if(VAR  != 40)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= VAR)
if(VAR  <= 30)
if(VAR [VAR] <= 30)
if(VAR  >= NULL)
if(VAR  <= 10)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= 10)
if(VAR  <= NULL)
if(VAR  >= NULL)
if(VAR  <= 10)
if(VAR [VAR] == 20)
if(VAR [VAR] >= 20)
if(VAR [VAR] == 30)
if(VAR  == 10)
if(VAR [VAR] == VAR)
if(VAR  >= 30)
if(VAR  == 20)
if(VAR  != 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] != NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] <= 30)
if(VAR [VAR] != 40)
if(VAR [VAR] != 30)
if(VAR  <= NULL)
if(VAR [VAR] == 20)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= 40)
if(VAR [VAR] != 20)
if(VAR  == 20)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != VAR)
if(VAR  <= VAR)
if(VAR  >= VAR)
if(VAR [VAR] >= 10)
if(VAR [VAR] != 10)
if(VAR [VAR] != 10)
if(VAR  == VAR)
if(VAR [VAR] != 30)
if(VAR  != NULL)
if(VAR  != VAR)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 40)
if(VAR [VAR] != 10)
if(VAR [VAR] != 40)
if(VAR  != NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] <= VAR)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= 10)
if(VAR  != 20)
if(VAR  <= 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= 30)
if(VAR [VAR] != VAR)
if(VAR  != NULL)
if(VAR [VAR] == 10)
if(VAR  != 20)
if(VAR [VAR] == 10)
if(VAR [VAR] >= 20)
if(VAR  != 20)
if(VAR [VAR] == 30)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= 10)
if(VAR  <= 20)
if(VAR [VAR] == VAR)
if(VAR  != 10)
if(VAR  <= 40)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= NULL)
if(VAR  <= 40)
if(VAR [VAR] <= VAR)
if(VAR  == 30)
if(VAR  != VAR)
if(VAR  == 20)
if(VAR [VAR] != NULL)
if(VAR  <= 40)
if(VAR  >= 10)
if(VAR  >= 10)
if(VAR  <= NULL)
if(VAR [VAR] >= 10)
if(VAR  <= 20)
if(VAR  <= VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] != 20)
if(VAR [VAR] <= 20)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 20)
if(VAR  != 40)
if(VAR [VAR] <= NULL)
if(VAR [VAR] <= VAR)
if(VAR [VAR] != NULL)
if(VAR  == 40)
if(VAR [VAR] != 10)
if(VAR [VAR] == 40)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= 40)
if(VAR  == 40)
if(VAR  >= VAR)
if(VAR  <= 30)
if(VAR  != 30)
if(VAR  == 20)
if(VAR  == NULL)
if(VAR [VAR] >= NULL)
if(VAR  == VAR)
if(VAR [VAR] != 10)
if(VAR [VAR] != NULL)
if(VAR  <= 40)
if(VAR  == 10)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= VAR)
if(VAR  <= 10)
if(VAR [VAR] == 40)
if(VAR [VAR] != 10)
if(VAR  == 20)
if(VAR  != 20)
if(VAR  >= 20)
if(VAR  <= NULL)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= 20)
if(VAR [VAR] != 20)
if(VAR [VAR] <= 30)
if(VAR  == 30)
if(VAR [VAR] == 30)
if(VAR  != NULL)
if(VAR  <= VAR)
if(VAR  <= 40)
if(VAR  >= 10)
if(VAR  <= 30)
if(VAR [VAR] != 40)
if(VAR  <= 30)
if(VAR  == 30)
if(VAR  != VAR)
if(VAR [VAR] >= 30)
if(VAR [VAR] != NULL)
if(VAR  != 30)
if(VAR [VAR] <= 10)
if(VAR  != 40)
if(VAR [VAR] <= VAR)
if(VAR  >= 20)
if(VAR  != 20)
if(VAR  >= 40)
if(VAR [VAR] != NULL)
if(VAR  <= 20)
if(VAR [VAR] <= 10)
if(VAR  >= VAR)
if(VAR [VAR] >= NULL)
if(VAR  <= 40)
if(VAR  != 10)
if(VAR [VAR] >= 40)
if(VAR  != 20)
if(VAR [VAR] == 40)
if(VAR  == 40)
if(VAR  <= NULL)
if(VAR  == NULL)
if(VAR  <= 20)
if(VAR [VAR] >= 30)
if(VAR  == 30)
if(VAR [VAR] != 20)
if(VAR  != 40)
if(VAR  == VAR)
if(VAR [VAR] <= 30)
if(VAR  != 40)
if(VAR  <= VAR)
if(VAR  >= 20)
if(VAR [VAR] >= 20)
if(VAR  <= 10)
if(VAR  == 10)
if(VAR [VAR] >= 20)
if(VAR  >= 40)
if(VAR  != 30)
if(VAR  >= 10)
if(VAR  != 20)
if(VAR  != VAR)
if(VAR [VAR] == 30)
if(VAR [VAR] == 40)
if(VAR  != 20)
if(VAR  <= 20)
if(VAR [VAR] == 20)
if(VAR [VAR] >= NULL)
if(VAR  == 30)
if(VAR  <= VAR)
if(VAR [VAR] != VAR)
if(VAR [VAR] != VAR)
if(VAR  != 30)
if(VAR  >= NULL)
if(VAR [VAR] != 20)
if(VAR [VAR] >= 10)
if(VAR  != 40)
if(VAR [VAR] >= 10)
if(VAR  >= 30)
if(VAR  >= 10)
if(VAR  >= VAR)
if(VAR  <= 30)
if(VAR  == 40)
if(VAR [VAR] <= 30)
if(VAR  <= 30)
if(VAR  >= VAR)
if(VAR [VAR] >= 20)
if(VAR  >= 20)
if(VAR  <= 20)
if(VAR [VAR] >= NULL)
if(VAR  != NULL)
if(VAR [VAR] == 10)
if(VAR  == VAR)
if(VAR [VAR] == 30)
if(VAR  != 20)
if(VAR  >= 10)
if(VAR  == 40)
if(VAR [VAR] <= 40)
if(VAR [VAR] <= 20)
if(VAR [VAR] == 20)
if(VAR [VAR] <= NULL)
if(VAR  == 10)
if(VAR  == VAR)
if(VAR  != 40)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= 10)
if(VAR  >= 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] <= 40)
if(VAR [VAR] <= 40)
if(VAR  == VAR)
if(VAR [VAR] != 20)
if(VAR [VAR] != 10)
if(VAR [VAR] != 10)
if(VAR  != 40)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= 20)
if(VAR [VAR] == NULL)
if(VAR  == 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] == 40)
if(VAR [VAR] != 10)
if(VAR  >= 40)
if(VAR [VAR] != 20)
if(VAR  != 10)
if(VAR  != 10)
if(VAR  <= VAR)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= VAR)
if(VAR  == 40)
if(VAR [VAR] <= VAR)
if(VAR [VAR] != 20)
if(VAR  != 20)
if(VAR [VAR] == 20)
if(VAR [VAR] == NULL)
if(VAR  == 10)
if(VAR  != 10)
if(VAR  == 10)
if(VAR  == VAR)
if(VAR  <= NULL)
if(VAR [VAR] == VAR)
if(VAR  != 40)
if(VAR [VAR] >= NULL)
if(VAR  <= VAR)
if(VAR [VAR] >= 20)
if(VAR  == 40)
if(VAR  <= VAR)
if(VAR  <= NULL)
if(VAR  >= NULL)
if(VAR [VAR] <= 10)
if(VAR  == 20)
if(VAR  != 40)
if(VAR  <= 40)
if(VAR  != 20)
if(VAR  != VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] >= 30)
if(VAR  == 10)
if(VAR  == 30)
if(VAR [VAR] != 20)
if(VAR  == 20)
if(VAR  <= 30)
if(VAR [VAR] == 40)
if(VAR [VAR] == 20)
if(VAR  >= VAR)
if(VAR  == VAR)
if(VAR  >= NULL)
if(VAR  >= 10)
if(VAR  <= VAR)
if(VAR  <= 40)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 10)
if(VAR  == 30)
if(VAR [VAR] <= 20)
if(VAR  >= VAR)
if(VAR [VAR] <= 10)
if(VAR [VAR] != 20)
if(VAR  != 30)
if(VAR [VAR] >= 40)
if(VAR  != VAR)
if(VAR  >= VAR)
if(VAR [VAR] != 30)
if(VAR [VAR] == VAR)
if(VAR [VAR] != VAR)
if(VAR  >= 30)
if(VAR  <= 40)
if(VAR [VAR] == 10)
if(VAR  == VAR)
if(VAR  == 40)
if(VAR [VAR] != 20)
if(VAR [VAR] >= 20)
if(VAR [VAR] == NULL)
if(VAR [VAR] != NULL)
if(VAR [VAR] != NULL)
if(VAR  != VAR)
if(VAR  <= 10)
if(VAR [VAR] == 10)
if(VAR  <= VAR)
if(VAR  == 10)
if(VAR  >= 40)
if(VAR [VAR] <= NULL)
if(VAR  <= NULL)
if(VAR  <= 20)
if(VAR [VAR] == VAR)
if(VAR  == NULL)
if(VAR  != 40)
if(VAR  == 20)
if(VAR [VAR] >= 20)
if(VAR  <= NULL)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != 20)
if(VAR [VAR] != 30)
if(VAR  <= NULL)
if(VAR [VAR] != 20)
if(VAR [VAR] <= 30)
if(VAR  >= VAR)
if(VAR [VAR] == 40)
if(VAR  != 40)
if(VAR [VAR] >= 40)
if(VAR  >= 20)
if(VAR  != 40)
if(VAR [VAR] == 30)
if(VAR [VAR] <= 10)
if(VAR [VAR] == NULL)
if(VAR [VAR] >= 10)
if(VAR  >= 20)
if(VAR [VAR] != 10)
if(VAR [VAR] != NULL)
if(VAR  >= VAR)
if(VAR  == VAR)
if(VAR  == 30)
if(VAR [VAR] != 20)
if(VAR  != NULL)
if(VAR [VAR] == NULL)
if(VAR  == VAR)
if(VAR [VAR] >= 20)
if(VAR  != 10)
if(VAR  >= 30)
if(VAR  >= 20)
if(VAR [VAR] == 10)
if(VAR  >= 30)
if(VAR [VAR] != NULL)
if(VAR  >= NULL)
if(VAR [VAR] == 20)
if(VAR  == 10)
if(VAR [VAR] <= 40)
if(VAR [VAR] <= 40)
if(VAR  == 40)
if(VAR  != NULL)
if(VAR [VAR] == NULL)
if(VAR  != NULL)
if(VAR  == NULL)
if(VAR  != 30)
if(VAR [VAR] != 40)
if(VAR  <= 10)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= 10)
if(VAR [VAR] == NULL)
if(VAR  != 30)
if(VAR [VAR] <= 40)
if(VAR [VAR] != 10)
if(VAR  != 10)
if(VAR  >= 30)
if(VAR  >= 30)
if(VAR  == 40)
if(VAR  == 10)
if(VAR  != 20)
if(VAR [VAR] <= 20)
if(VAR  == 30)
if(VAR [VAR] >= 30)
if(VAR [VAR] >= 20)
if(VAR  != 10)
if(VAR [VAR] != VAR)
if(VAR  <= 30)
if(VAR  == VAR)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= NULL)
if(VAR  == 40)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= 30)
if(VAR  <= 20)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= 20)
if(VAR  <= 30)
if(VAR [VAR] >= 30)
if(VAR  == NULL)
if(VAR  <= 10)
if(VAR  == 10)
if(VAR  >= 30)
if(VAR  >= 30)
if(VAR  == 10)
if(VAR  <= 10)
if(VAR [VAR] != 30)
if(VAR [VAR] != 30)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 30)
if(VAR  >= VAR)
if(VAR  == VAR)
if(VAR  == NULL)
if(VAR  <= VAR)
if(VAR [VAR] != 30)
if(VAR [VAR] != 30)
if(VAR [VAR] == 40)
if(VAR [VAR] <= VAR)
if(VAR [VAR] <= VAR)
if(VAR  != 20)
if(VAR  == 10)
if(VAR [VAR] == 10)
if(VAR  >= 20)
if(VAR  >= 30)
if(VAR [VAR] == 40)
if(VAR  == 10)
if(VAR  == 40)
if(VAR  == 40)
if(VAR  != NULL)
if(VAR [VAR] >= 10)
if(VAR [VAR] <= 20)
if(VAR  != 10)
if(VAR [VAR] == 10)
if(VAR  <= VAR)
if(VAR [VAR] != 40)
if(VAR  != 30)
if(VAR [VAR] >= 10)
if(VAR [VAR] == NULL)
if(VAR [VAR] <= 20)
if(VAR  <= NULL)
if(VAR  >= 30)
if(VAR [VAR] == 40)
if(VAR  == 30)
if(VAR [VAR] == 30)
if(VAR [VAR] != 20)
if(VAR [VAR] >= 10)
if(VAR [VAR] != 40)
if(VAR  >= 10)
if(VAR  != 30)
if(VAR [VAR] <= 40)
if(VAR  == 30)
if(VAR  == 30)
if(VAR  == 30)
if(VAR [VAR] == 30)
if(VAR [VAR] == 20)
if(VAR  >= VAR)
if(VAR  == 10)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= 10)
if(VAR  == 40)
if(VAR [VAR] != 10)
if(VAR  >= VAR)
if(VAR [VAR] != NULL)
if(VAR  <= 20)
if(VAR  <= 10)
if(VAR [VAR] != 10)
if(VAR [VAR] >= 30)
if(VAR [VAR] != 10)
if(VAR  <= 20)
if(VAR  != 20)
if(VAR [VAR] == 10)
if(VAR  != 40)
if(VAR  != 10)
if(VAR  != 10)
if(VAR  <= 30)
if(VAR [VAR] == 20)
if(VAR [VAR] >= 40)
if(VAR  == 20)
if(VAR [VAR] != NULL)
if(VAR  >= VAR)
if(VAR  != 40)
if(VAR [VAR] != 20)
if(VAR  <= NULL)
if(VAR [VAR] >= 20)
if(VAR  <= NULL)
if(VAR  != NULL)
if(VAR  >= NULL)
if(VAR [VAR] == 40)
if(VAR  <= VAR)
if(VAR [VAR] <= 10)
if(VAR [VAR] == NULL)
if(VAR [VAR] == 10)
if(VAR [VAR] == 40)
if(VAR  == NULL)
if(VAR [VAR] <= 40)
if(VAR  != 30)
if(VAR [VAR] != VAR)
if(VAR  != 30)
if(VAR [VAR] == 30)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= NULL)
if(VAR  >= 20)
if(VAR  >= 30)
if(VAR [VAR] != 40)
if(VAR  != VAR)
if(VAR [VAR] <= 20)
if(VAR  <= 40)
if(VAR [VAR] != VAR)
if(VAR [VAR] <= VAR)
if(VAR  != 40)
if(VAR [VAR] == 30)
if(VAR  != VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] >= VAR)
if(VAR  != 20)
if(VAR  == 10)
if(VAR  >= 10)
if(VAR  <= 40)
if(VAR  != NULL)
if(VAR [VAR] != 40)
if(VAR  >= 40)
if(VAR  == VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] >= 20)
if(VAR [VAR] != 10)
if(VAR [VAR] != 20)
if(VAR  <= 30)
if(VAR [VAR] == VAR)
if(VAR [VAR] >= 10)
if(VAR  == 10)
if(VAR  >= 10)
if(VAR [VAR] <= 30)
if(VAR  >= VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] != 30)
if(VAR [VAR] == NULL)
if(VAR [VAR] == VAR)
if(VAR  == 30)
if(VAR [VAR] == 30)
if(VAR  == 10)
if(VAR  >= NULL)
if(VAR [VAR] <= 30)
if(VAR  == 30)
if(VAR  != 20)
if(VAR [VAR] == 10)
if(VAR  == 10)
if(VAR  != VAR)
if(VAR  <= VAR)
if(VAR [VAR] == 40)
if(VAR [VAR] != VAR)
if(VAR [VAR] != 30)
if(VAR  != 30)
if(VAR  != 10)
if(VAR [VAR] != 40)
if(VAR [VAR] >= NULL)
if(VAR  <= VAR)
if(VAR  <= 20)
if(VAR [VAR] != VAR)
if(VAR [VAR] == 40)
if(VAR [VAR] <= 20)
if(VAR  != VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= NULL)
if(VAR [VAR] <= NULL)
if(VAR  != 20)
if(VAR  == 20)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 30)
if(VAR [VAR] == NULL)
if(VAR  >= 40)
if(VAR  == 20)
if(VAR [VAR] == 10)
if(VAR  <= 10)
if(VAR [VAR] != 10)
if(VAR [VAR] != 30)
if(VAR  <= NULL)
if(VAR  == 10)
if(VAR [VAR] == NULL)
if(VAR  == 10)
if(VAR [VAR] == NULL)
if(VAR  != 30)
if(VAR  >= VAR)
if(VAR [VAR] <= VAR)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 10)
if(VAR  != VAR)
if(VAR [VAR] <= VAR)
if(VAR  != 30)
if(VAR [VAR] >= 30)
if(VAR  != VAR)
if(VAR  != 30)
if(VAR [VAR] != 10)
if(VAR  != 20)
if(VAR [VAR] >= NULL)
if(VAR  == 30)
if(VAR [VAR] >= 10)
if(VAR  == 10)
if(VAR [VAR] != 20)
if(VAR [VAR] != 40)
if(VAR [VAR] != 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] >= 20)
if(VAR  >= 40)
if(VAR [VAR] == 20)
if(VAR  <= 20)
if(VAR [VAR] >= 30)
if(VAR  <= 10)
if(VAR [VAR] != 40)
if(VAR [VAR] <= 20)
if(VAR [VAR] == 40)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= VAR)
if(VAR  == 10)
if(VAR  != VAR)
if(VAR [VAR] <= 40)
if(VAR  >= 10)
if(VAR  == NULL)
if(VAR [VAR] <= 30)
if(VAR  >= 40)
if(VAR  == 40)
if(VAR [VAR] != 10)
if(VAR [VAR] != 40)
if(VAR [VAR] <= 40)
if(VAR  >= 20)
if(VAR  >= 20)
if(VAR  <= NULL)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == 10)
if(VAR [VAR] <= VAR)
if(VAR  <= NULL)
if(VAR  >= VAR)
if(VAR  <= VAR)
if(VAR  == VAR)
if(VAR [VAR] == 30)
if(VAR [VAR] <= NULL)
if(VAR  == 10)
if(VAR  <= 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] <= 30)
if(VAR [VAR] == 10)
if(VAR  != 40)
if(VAR [VAR] != 30)
if(VAR [VAR] <= 10)
if(VAR  != 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == 30)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= 20)
if(VAR  >= VAR)
if(VAR  != 10)
if(VAR  >= 30)
if(VAR [VAR] != 10)
if(VAR [VAR] <= 20)
if(VAR  <= 20)
if(VAR  <= 20)
if(VAR  <= 30)
if(VAR [VAR] != 20)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != 10)
if(VAR  != VAR)
if(VAR  <= VAR)
if(VAR  <= 30)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= 10)
if(VAR [VAR] <= 20)
if(VAR  >= NULL)
if(VAR [VAR] == VAR)
if(VAR [VAR] != 30)
if(VAR  >= NULL)
if(VAR [VAR] != 40)
if(VAR  == NULL)
if(VAR [VAR] == NULL)
if(VAR  != 40)
if(VAR  >= 40)
if(VAR  >= VAR)
if(VAR [VAR] >= 30)
if(VAR [VAR] >= 40)
if(VAR [VAR] != 20)
if(VAR  == 40)
if(VAR [VAR] <= 10)
if(VAR  >= VAR)
if(VAR  <= 10)
if(VAR  >= NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != VAR)
if(VAR [VAR] != VAR)
if(VAR  != 20)
if(VAR  <= 20)
if(VAR  >= 40)
if(VAR [VAR] == NULL)
if(VAR  == 40)
if(VAR  >= NULL)
if(VAR [VAR] != VAR)
if(VAR [VAR] != 30)
if(VAR  >= 10)
if(VAR [VAR] >= 20)
if(VAR [VAR] == 10)
if(VAR  != 30)
if(VAR [VAR] <= 40)
if(VAR [VAR] != 10)
if(VAR  >= NULL)
if(VAR [VAR] <= 40)
if(VAR  == 20)
if(VAR  >= 20)
if(VAR [VAR] != 30)
if(VAR  <= NULL)
if(VAR  >= 30)
if(VAR  >= 30)
if(VAR  >= 40)
if(VAR  != NULL)
if(VAR  <= VAR)
if(VAR  != 20)
if(VAR [VAR] != 40)
if(VAR [VAR] <= 10)
if(VAR [VAR] >= 30)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= VAR)
if(VAR  >= 20)
if(VAR  <= NULL)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= 30)
if(VAR  >= 40)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= 20)
if(VAR  == 40)
if(VAR [VAR] >= 40)
if(VAR  >= VAR)
if(VAR [VAR] <= VAR)
if(VAR  <= NULL)
if(VAR  != 10)
if(VAR  >= 10)
if(VAR  >= 10)
if(VAR  <= 30)
if(VAR [VAR] <= 10)
if(VAR  != 40)
if(VAR  == 20)
if(VAR  >= 10)
if(VAR [VAR] != 10)
if(VAR  <= 10)
if(VAR [VAR] == 20)
if(VAR  == 10)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != 30)
if(VAR  == 40)
if(VAR  == 30)
if(VAR [VAR] <= 30)
if(VAR  >= 10)
if(VAR [VAR] == VAR)
if(VAR [VAR] >= NULL)
if(VAR  <= NULL)
if(VAR  <= 30)
if(VAR  <= VAR)
if(VAR  == 20)
if(VAR  == VAR)
if(VAR  == 10)
if(VAR  == 40)
if(VAR [VAR] <= 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= 30)
if(VAR  != NULL)
if(VAR  <= NULL)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != 30)
if(VAR  != NULL)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= VAR)
if(VAR [VAR] != 40)
if(VAR [VAR] <= VAR)
if(VAR  >= 20)
if(VAR [VAR] <= 10)
if(VAR  != 30)
if(VAR  <= 20)
if(VAR  != 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != 10)
if(VAR  >= 40)
if(VAR [VAR] != 10)
if(VAR [VAR] == 10)
if(VAR [VAR] != 10)
if(VAR [VAR] >= 10)
if(VAR  >= 30)
if(VAR  != 10)
if(VAR [VAR] >= 20)
if(VAR  <= VAR)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 20)
if(VAR  >= 10)
if(VAR [VAR] != VAR)
if(VAR [VAR] >= 10)
if(VAR  <= VAR)
if(VAR  != VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] != 10)
if(VAR  != VAR)
if(VAR [VAR] != NULL)
if(VAR [VAR] != VAR)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= NULL)
if(VAR  <= 20)
if(VAR  >= 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] >= 20)
if(VAR  >= NULL)
if(VAR  != 40)
if(VAR [VAR] >= 20)
if(VAR  == 40)
if(VAR  >= 10)
if(VAR  != VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] != 20)
if(VAR  == NULL)
if(VAR [VAR] != 40)
if(VAR  != 30)
if(VAR  == VAR)
if(VAR  <= VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] == 40)
if(VAR  == 40)
if(VAR  != NULL)
if(VAR  != NULL)
if(VAR  != 20)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 20)
if(VAR  <= NULL)
if(VAR  == 10)
if(VAR  >= 10)
if(VAR  == 30)
if(VAR [VAR] <= 40)
if(VAR  <= 40)
if(VAR [VAR] == 10)
if(VAR [VAR] <= 20)
if(VAR  >= VAR)
if(VAR  >= VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= VAR)
if(VAR  == 30)
if(VAR  <= 20)
if(VAR  >= 30)
if(VAR  >= VAR)
if(VAR  != 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] == 20)
if(VAR [VAR] == 30)
if(VAR  <= 30)
if(VAR [VAR] >= 40)
if(VAR  <= 30)
if(VAR [VAR] >= 10)
if(VAR  >= VAR)
if(VAR  != 10)
if(VAR [VAR] != 40)
if(VAR [VAR] != 40)
if(VAR [VAR] != 20)
if(VAR [VAR] >= VAR)
if(VAR [VAR] <= 10)
if(VAR  == 10)
if(VAR  >= 40)
if(VAR [VAR] == 10)
if(VAR [VAR] == 20)
if(VAR  != 30)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= 20)
if(VAR  == VAR)
if(VAR [VAR] == 30)
if(VAR [VAR] != 30)
if(VAR [VAR] == 10)
if(VAR [VAR] >= 30)
if(VAR [VAR] == 20)
if(VAR [VAR] != 20)
if(VAR  == 20)
if(VAR  != 40)
if(VAR  != NULL)
if(VAR  != 30)
if(VAR  != NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= 10)
if(VAR  != VAR)
if(VAR  == 30)
if(VAR  != 20)
if(VAR [VAR] <= 10)
if(VAR  >= NULL)
if(VAR  != NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] == VAR)
if(VAR [VAR] == 40)
if(VAR  <= 10)
if(VAR  != 20)
if(VAR [VAR] <= 20)
if(VAR [VAR] == 10)
if(VAR [VAR] == 40)
if(VAR  <= NULL)
if(VAR [VAR] == VAR)
if(VAR [VAR] >= 20)
if(VAR  >= 40)
if(VAR  != 40)
if(VAR [VAR] == 20)
if(VAR [VAR] >= VAR)
if(VAR  == 20)
if(VAR  == VAR)
if(VAR [VAR] != 20)
if(VAR [VAR] <= 30)
if(VAR  != NULL)
if(VAR  != 10)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != 20)
if(VAR [VAR] != 20)
if(VAR [VAR] <= 20)
if(VAR  != 10)
if(VAR  <= VAR)
if(VAR  == 30)
if(VAR  >= 10)
if(VAR  == VAR)
if(VAR  >= 30)
if(VAR  >= 30)
if(VAR [VAR] >= 40)
if(VAR  != 30)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] == 20)
if(VAR  == 30)
if(VAR [VAR] != 40)
if(VAR [VAR] == 20)
if(VAR [VAR] <= VAR)
if(VAR  >= NULL)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= 30)
if(VAR  <= 40)
if(VAR [VAR] == NULL)
if(VAR  != 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] >= 10)
if(VAR  != NULL)
if(VAR  == NULL)
if(VAR  >= 10)
if(VAR  >= 10)
if(VAR [VAR] != 30)
if(VAR  != VAR)
if(VAR [VAR] != NULL)
if(VAR  <= NULL)
if(VAR [VAR] != 20)
if(VAR [VAR] <= 20)
if(VAR  <= 30)
if(VAR  >= 10)
if(VAR [VAR] <= NULL)
if(VAR  == 10)
if(VAR  != 30)
if(VAR [VAR] == 30)
if(VAR [VAR] >= VAR)
if(VAR  <= 40)
if(VAR  <= 30)
if(VAR  == 40)
if(VAR  != 10)
if(VAR  >= 20)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= VAR)
if(VAR  != 40)
if(VAR [VAR] == 30)
if(VAR [VAR] != 30)
if(VAR  <= VAR)
if(VAR  != 30)
if(VAR  >= 20)
if(VAR  != 30)
if(VAR  == 20)
if(VAR  <= 10)
if(VAR [VAR] >= NULL)
if(VAR  != 20)
if(VAR  <= 30)
if(VAR  >= 10)
if(VAR [VAR] == NULL)
if(VAR [VAR] <= NULL)
if(VAR  <= NULL)
if(VAR [VAR] >= 30)
if(VAR  <= VAR)
if(VAR  >= VAR)
if(VAR [VAR] <= 30)
if(VAR [VAR] == VAR)
if(VAR  == 20)
if(VAR  <= 10)
if(VAR  != NULL)
if(VAR  != NULL)
if(VAR [VAR] <= 40)
if(VAR [VAR] != 30)
if(VAR [VAR] == 10)
if(VAR [VAR] <= 30)
if(VAR  >= 30)
if(VAR  >= NULL)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= 10)
if(VAR  != VAR)
if(VAR  != 10)
if(VAR [VAR] != VAR)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 30)
if(VAR  != 40)
if(VAR [VAR] >= 10)
if(VAR  >= 10)
if(VAR [VAR] == NULL)
if(VAR  <= NULL)
if(VAR  == VAR)
if(VAR  == 20)
if(VAR [VAR] <= VAR)
if(VAR [VAR] <= VAR)
if(VAR  != VAR)
if(VAR [VAR] <= 20)
if(VAR  == NULL)
if(VAR [VAR] <= VAR)
if(VAR [VAR] <= VAR)
if(VAR  >= VAR)
if(VAR [VAR] != 10)
if(VAR  >= 40)
if(VAR [VAR] == 20)
if(VAR [VAR] != NULL)
if(VAR [VAR] != 10)
if(VAR  <= VAR)
if(VAR  >= VAR)
if(VAR  == 30)
if(VAR [VAR] >= 20)
if(VAR  == 30)
if(VAR  <= 20)
if(VAR [VAR] <= 20)
if(VAR  >= 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] >= 40)
if(VAR  >= 40)
if(VAR  <= VAR)
if(VAR [VAR] >= 10)
if(VAR [VAR] <= 40)
if(VAR [VAR] != 10)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != VAR)
if(VAR  != VAR)
if(VAR [VAR] == NULL)
if(VAR [VAR] == 30)
if(VAR  >= VAR)
if(VAR [VAR] <= 20)
if(VAR  == 20)
if(VAR  <= VAR)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= 20)
if(VAR  >= 30)
if(VAR [VAR] != 20)
if(VAR [VAR] <= VAR)
if(VAR  >= NULL)
if(VAR [VAR] == 20)
if(VAR  != NULL)
if(VAR [VAR] != NULL)
if(VAR [VAR] != VAR)
if(VAR  >= VAR)
if(VAR [VAR] >= VAR)
if(VAR  <= 20)
if(VAR  <= VAR)
if(VAR [VAR] <= 20)
if(VAR  != 10)
if(VAR  <= NULL)
if(VAR [VAR] != 30)
if(VAR  != 20)
if(VAR  <= NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] == 20)
if(VAR  <= NULL)
if(VAR  <= 40)
if(VAR  <= 10)
if(VAR  != 30)
if(VAR  <= 10)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= 20)
if(VAR [VAR] != NULL)
if(VAR  != 40)
if(VAR [VAR] != 40)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= 40)
if(VAR  != 10)
if(VAR  >= NULL)
if(VAR [VAR] >= VAR)
if(VAR  >= 10)
if(VAR  >= 20)
if(VAR [VAR] == 20)
if(VAR [VAR] == 30)
if(VAR  == 10)
if(VAR  == 20)
if(VAR [VAR] <= NULL)
if(VAR  <= 30)
if(VAR [VAR] == 20)
if(VAR [VAR] <= NULL)
if(VAR  != VAR)
if(VAR [VAR] >= 20)
if(VAR  != 40)
if(VAR [VAR] <= 40)
if(VAR  <= 20)
if(VAR [VAR] != 40)
if(VAR [VAR] >= 40)
if(VAR [VAR] != 10)
if(VAR  != 30)
if(VAR  >= VAR)
if(VAR  != 20)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= NULL)
if(VAR  <= 40)
if(VAR [VAR] <= 20)
if(VAR [VAR] != 40)
if(VAR  != 10)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 20)
if(VAR  <= 20)
if(VAR  >= 30)
if(VAR  <= VAR)
if(VAR  <= 40)
if(VAR  == 10)
if(VAR [VAR] == VAR)
if(VAR  == 20)
if(VAR  >= VAR)
if(VAR  <= NULL)
if(VAR [VAR] <= 10)
if(VAR  != 10)
if(VAR [VAR] <= 30)
if(VAR  >= 30)
if(VAR [VAR] != 10)
if(VAR  <= 10)
if(VAR [VAR] != 10)
if(VAR  <= 10)
if(VAR  != NULL)
if(VAR  != 30)
if(VAR  >= 30)
if(VAR [VAR] >= 20)
if(VAR  <= VAR)
if(VAR [VAR] == 20)
if(VAR  != 20)
if(VAR  >= NULL)
if(VAR [VAR] <= 10)
if(VAR  <= VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] != VAR)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != NULL)
if(VAR  != 20)
if(VAR  != 30)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] >= 40)
if(VAR  == 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == NULL)
if(VAR [VAR] == 10)
if(VAR [VAR] != 30)
if(VAR [VAR] == 30)
if(VAR  >= 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] == 30)
if(VAR  == VAR)
if(VAR  != NULL)
if(VAR  <= 30)
if(VAR  == 30)
if(VAR  != 10)
if(VAR  <= 30)
if(VAR  <= 20)
if(VAR [VAR] >= 40)
if(VAR [VAR] != 40)
if(VAR  == 10)
if(VAR  == 20)
if(VAR [VAR] >= 30)
if(VAR [VAR] != VAR)
if(VAR  != 10)
if(VAR  == 20)
if(VAR  == 10)
if(VAR  >= 20)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= 30)
if(VAR  == NULL)
if(VAR [VAR] != 20)
if(VAR  == 30)
if(VAR  <= VAR)
if(VAR  != 10)
if(VAR [VAR] <= NULL)
if(VAR  != VAR)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= 40)
if(VAR [VAR] != 10)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != 20)
if(VAR  != NULL)
if(VAR [VAR] <= 10)
if(VAR  == 30)
if(VAR  == NULL)
if(VAR [VAR] != VAR)
if(VAR [VAR] == 10)
if(VAR  <= 30)
if(VAR [VAR] <= 10)
if(VAR  >= 10)
if(VAR  == 20)
if(VAR  != 40)
if(VAR [VAR] == 10)
if(VAR  >= 40)
if(VAR [VAR] >= VAR)
if(VAR  != 40)
if(VAR  <= 40)
if(VAR [VAR] <= 40)
if(VAR  >= VAR)
if(VAR [VAR] <= 30)
if(VAR  != 30)
if(VAR  == 40)
if(VAR [VAR] != 20)
if(VAR  != VAR)
if(VAR  == 30)
if(VAR  >= 40)
if(VAR [VAR] <= VAR)
if(VAR  >= 20)
if(VAR  != 40)
if(VAR  == NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= NULL)
if(VAR  != NULL)
if(VAR  != NULL)
if(VAR  != 40)
if(VAR [VAR] == VAR)
if(VAR  >= NULL)
if(VAR  != 10)
if(VAR  <= 30)
if(VAR  == 10)
if(VAR  != 30)
if(VAR [VAR] <= 40)
if(VAR  <= 10)
if(VAR  <= 10)
if(VAR  != VAR)
if(VAR [VAR] >= 40)
if(VAR  == 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] != 30)
if(VAR  <= 20)
if(VAR [VAR] != VAR)
if(VAR [VAR] == 40)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= 10)
if(VAR [VAR] == NULL)
if(VAR  >= 10)
if(VAR  <= 10)
if(VAR [VAR] == VAR)
if(VAR [VAR] <= 20)
if(VAR  != VAR)
if(VAR [VAR] == 20)
if(VAR [VAR] != 20)
if(VAR [VAR] != 10)
if(VAR [VAR] >= NULL)
if(VAR  != 10)
if(VAR [VAR] >= NULL)
if(VAR  != NULL)
if(VAR  >= 10)
if(VAR [VAR] <= VAR)
if(VAR  == VAR)
if(VAR [VAR] >= 40)
if(VAR [VAR] == 10)
if(VAR  <= 40)
if(VAR  != 20)
if(VAR  != 10)
if(VAR  >= 10)
if(VAR [VAR] == 30)
if(VAR  != VAR)
if(VAR  == 30)
if(VAR  <= NULL)
if(VAR [VAR] == 20)
if(VAR [VAR] <= VAR)
if(VAR  != 40)
if(VAR [VAR] == VAR)
if(VAR  <= 10)
if(VAR  == 40)
if(VAR  <= 40)
if(VAR  >= 20)
if(VAR  <= 10)
if(VAR  == 10)
if(VAR  >= 20)
if(VAR  != 40)
if(VAR  <= VAR)
if(VAR  <= 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == VAR)
if(VAR  != 40)
if(VAR [VAR] != 30)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= 30)
if(VAR [VAR] != NULL)
if(VAR  == 30)
if(VAR [VAR] <= 40)
if(VAR  >= 10)
if(VAR  != 10)
if(VAR [VAR] != VAR)
if(VAR  >= NULL)
if(VAR [VAR] >= NULL)
if(VAR  != 20)
if(VAR [VAR] != 10)
if(VAR [VAR] >= 40)
if(VAR  == NULL)
if(VAR  == VAR)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == 40)
if(VAR  >= 40)
if(VAR  != 20)
if(VAR  >= 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == VAR)
if(VAR  != 20)
if(VAR [VAR] >= 10)
if(VAR  >= 30)
if(VAR  == VAR)
if(VAR [VAR] != 40)
if(VAR [VAR] >= 10)
if(VAR  != 30)
if(VAR [VAR] == VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] == 30)
if(VAR  <= 40)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= NULL)
if(VAR  == 10)
if(VAR  <= 40)
if(VAR  >= VAR)
if(VAR [VAR] >= 10)
if(VAR [VAR] <= 40)
if(VAR  <= NULL)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= 10)
if(VAR [VAR] == 10)
if(VAR [VAR] <= 10)
if(VAR [VAR] == 10)
if(VAR [VAR] >= VAR)
if(VAR  == 10)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == 10)
if(VAR  >= 40)
if(VAR  >= 30)
if(VAR [VAR] == 30)
if(VAR [VAR] == 30)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != NULL)
if(VAR [VAR] >= 30)
if(VAR  >= 30)
if(VAR  != VAR)
if(VAR  >= 20)
if(VAR [VAR] != 40)
if(VAR  <= NULL)
if(VAR  != VAR)
if(VAR  == 30)
if(VAR  != NULL)
if(VAR  != NULL)
if(VAR  <= 20)
if(VAR [VAR] == NULL)
if(VAR [VAR] == 40)
if(VAR  != 30)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= 20)
if(VAR  != NULL)
if(VAR [VAR] != 20)
if(VAR  <= 30)
if(VAR [VAR] >= 20)
if(VAR [VAR] != 10)
if(VAR [VAR] >= 30)
if(VAR  != 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] == NULL)
if(VAR  >= 10)
if(VAR [VAR] >= 10)
if(VAR  == 30)
if(VAR [VAR] == 10)
if(VAR  == VAR)
if(VAR  != 10)
if(VAR [VAR] >= 10)
if(VAR  == 40)
if(VAR  == 20)
if(VAR  != VAR)
if(VAR [VAR] <= 30)
if(VAR  == 20)
if(VAR  <= 40)
if(VAR [VAR] != 30)
if(VAR [VAR] != NULL)
if(VAR  <= NULL)
if(VAR  <= 20)
if(VAR [VAR] <= 40)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= 30)
if(VAR [VAR] != 30)
if(VAR  >= 40)
if(VAR [VAR] == 10)
if(VAR  == 10)
if(VAR  <= 10)
if(VAR [VAR] == NULL)
if(VAR  >= 30)
if(VAR  == 40)
if(VAR [VAR] <= NULL)
if(VAR [VAR] == 20)
if(VAR [VAR] != VAR)
if(VAR  >= 20)
if(VAR [VAR] <= 40)
if(VAR  != VAR)
if(VAR  == VAR)
if(VAR  == VAR)
if(VAR  >= 20)
if(VAR  >= 40)
if(VAR [VAR] != 20)
if(VAR  >= 10)
if(VAR [VAR] != NULL)
if(VAR [VAR] == 30)
if(VAR  >= 30)
if(VAR  <= VAR)
if(VAR [VAR] == VAR)
if(VAR  >= VAR)
if(VAR  != NULL)
if(VAR  >= NULL)
if(VAR [VAR] >= 30)
if(VAR  <= 30)
if(VAR [VAR] != NULL)
if(VAR  <= 30)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == 10)
if(VAR [VAR] == NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] != NULL)
if(VAR  != 40)
if(VAR  == 30)
if(VAR [VAR] >= 10)
if(VAR [VAR] == 40)
if(VAR  != 40)
if(VAR [VAR] != 20)
if(VAR  == VAR)
if(VAR [VAR] != 10)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 10)
if(VAR [VAR] == NULL)
if(VAR  <= 10)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= NULL)
if(VAR  >= 10)
if(VAR  <= NULL)
if(VAR [VAR] >= VAR)
if(VAR  == 10)
if(VAR  == 40)
if(VAR  <= NULL)
if(VAR  >= 20)
if(VAR  != 20)
if(VAR  != 10)
if(VAR [VAR] == VAR)
if(VAR  >= VAR)
if(VAR [VAR] >= 20)
if(VAR  != NULL)
if(VAR [VAR] != NULL)
if(VAR [VAR] == NULL)
if(VAR  != 30)
if(VAR [VAR] <= 30)
if(VAR  == VAR)
if(VAR  >= NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 10)
if(VAR  != NULL)
if(VAR [VAR] <= 40)
if(VAR  <= 10)
if(VAR  != VAR)
if(VAR  <= 10)
if(VAR  != 10)
if(VAR [VAR] == VAR)
if(VAR [VAR] == NULL)
if(VAR [VAR] != VAR)
if(VAR  >= 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] == VAR)
if(VAR  >= 30)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= VAR)
if(VAR  != VAR)
if(VAR  >= VAR)
if(VAR [VAR] <= NULL)
if(VAR  != 10)
if(VAR [VAR] >= 20)
if(VAR  <= 40)
if(VAR [VAR] != 20)
if(VAR [VAR] <= 30)
if(VAR  != 20)
if(VAR [VAR] != VAR)
if(VAR  >= 30)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= 40)
if(VAR  >= NULL)
if(VAR  == 30)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= 30)
if(VAR [VAR] == 40)
if(VAR  >= 10)
if(VAR [VAR] == 30)
if(VAR  == 20)
if(VAR  != NULL)
if(VAR [VAR] <= NULL)
if(VAR  != 10)
if(VAR [VAR] == 40)
if(VAR  != 10)
if(VAR [VAR] != 10)
if(VAR  != 40)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != 30)
if(VAR  != 40)
if(VAR [VAR] == 20)
if(VAR  == 20)
if(VAR  == 20)
if(VAR [VAR] != VAR)
if(VAR  != 10)
if(VAR  >= 40)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= NULL)
if(VAR  != 30)
if(VAR [VAR] >= NULL)
if(VAR  >= 20)
if(VAR  == 10)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= 20)
if(VAR  == 10)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= VAR)
if(VAR  != 40)
if(VAR  != 20)
if(VAR  != VAR)
if(VAR  == NULL)
if(VAR [VAR] >= NULL)
if(VAR  >= 10)
if(VAR [VAR] != NULL)
if(VAR [VAR] == 20)
if(VAR  >= NULL)
if(VAR [VAR] <= 40)
if(VAR  <= 10)
if(VAR  == 20)
if(VAR [VAR] <= VAR)
if(VAR [VAR] == 10)
if(VAR [VAR] != 10)
if(VAR  <= 40)
if(VAR [VAR] == 20)
if(VAR  == 20)
if(VAR  <= 10)
if(VAR [VAR] >= 30)
if(VAR  != NULL)
if(VAR [VAR] != 30)
if(VAR  <= VAR)
if(VAR [VAR] != VAR)
if(VAR  == VAR)
if(VAR  <= NULL)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= 30)
if(VAR [VAR] != 30)
if(VAR  == 10)
if(VAR  == 20)
if(VAR [VAR] == VAR)
if(VAR  >= VAR)
if(VAR [VAR] >= 10)
if(VAR  == NULL)
if(VAR  != NULL)
if(VAR [VAR] != 30)
if(VAR  == 20)
if(VAR  <= NULL)
if(VAR  != 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] >= 40)
if(VAR  <= VAR)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= 20)
if(VAR  != 10)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= 30)
if(VAR  <= 30)
if(VAR  <= VAR)
if(VAR  == 10)
if(VAR  == 30)
if(VAR  != NULL)
if(VAR  <= 20)
if(VAR [VAR] != NULL)
if(VAR  <= 20)
if(VAR [VAR] <= 10)
if(VAR  >= VAR)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= 40)
if(VAR  >= 30)
if(VAR  == 40)
if(VAR  <= 30)
if(VAR [VAR] >= 30)
if(VAR  >= 10)
if(VAR [VAR] >= NULL)
if(VAR  <= 40)
if(VAR  != NULL)
if(VAR  >= 10)
if(VAR  >= 30)
if(VAR  <= NULL)
if(VAR [VAR] <= VAR)
if(VAR  == 40)
if(VAR [VAR] != 10)
if(VAR  <= 10)
if(VAR [VAR] != 20)
if(VAR  != 30)
if(VAR  <= 40)
if(VAR  <= 30)
if(VAR  >= 20)
if(VAR [VAR] == NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] <= 30)
if(VAR  >= 40)
if(VAR [VAR] <= VAR)
if(VAR  <= NULL)
if(VAR  >= 10)
if(VAR  >= 30)
if(VAR [VAR] == 20)
if(VAR  != 10)
if(VAR [VAR] >= 30)
if(VAR [VAR] >= VAR)
if(VAR  != 40)
if(VAR [VAR] == 40)
if(VAR  == VAR)
if(VAR  <= NULL)
if(VAR  == 30)
if(VAR [VAR] <= NULL)
if(VAR  == NULL)
if(VAR [VAR] != 30)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= NULL)
if(VAR  <= VAR)
if(VAR  >= 10)
if(VAR  >= VAR)
if(VAR  == 40)
if(VAR  >= 10)
if(VAR [VAR] != NULL)
if(VAR [VAR] == 10)
if(VAR [VAR] == NULL)
if(VAR  == 20)
if(VAR  == NULL)
if(VAR  == VAR)
if(VAR [VAR] >= 30)
if(VAR [VAR] != VAR)
if(VAR  != 20)
if(VAR [VAR] >= 40)
if(VAR  != 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] == VAR)
if(VAR  == 30)
if(VAR  >= 40)
if(VAR [VAR] == 10)
if(VAR [VAR] >= VAR)
if(VAR  != NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] >= 10)
if(VAR  != 30)
if(VAR  == 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= NULL)
if(VAR [VAR] == NULL)
if(VAR  == 40)
if(VAR [VAR] == 20)
if(VAR  >= 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] <= 40)
if(VAR  <= 20)
if(VAR  == 30)
if(VAR  >= VAR)
if(VAR [VAR] != 10)
if(VAR [VAR] != NULL)
if(VAR [VAR] != 40)
if(VAR  == 40)
if(VAR  >= 10)
if(VAR [VAR] >= VAR)
if(VAR  >= VAR)
if(VAR  != 20)
if(VAR [VAR] >= 40)
if(VAR  <= NULL)
if(VAR  <= VAR)
if(VAR [VAR] >= 10)
if(VAR  == 40)
if(VAR [VAR] == 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= 10)
if(VAR  <= VAR)
if(VAR [VAR] == 20)
if(VAR [VAR] >= 10)
if(VAR  == 10)
if(VAR  <= 40)
if(VAR  >= 10)
if(VAR  != 40)
if(VAR  == 10)
if(VAR  == 20)
if(VAR  <= 40)
if(VAR  != 40)
if(VAR [VAR] != VAR)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= NULL)
if(VAR  <= 30)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == NULL)
if(VAR  >= 40)
if(VAR  != 10)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != 20)
if(VAR  != 20)
if(VAR [VAR] != 40)
if(VAR [VAR] >= 30)
if(VAR [VAR] != 30)
if(VAR [VAR] <= 30)
if(VAR  == NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] == 40)
if(VAR  == 40)
if(VAR  <= VAR)
if(VAR [VAR] != NULL)
if(VAR  >= VAR)
if(VAR  != 20)
if(VAR [VAR] != NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != 20)
if(VAR [VAR] == 30)
if(VAR [VAR] != 20)
if(VAR  <= VAR)
if(VAR  != 10)
if(VAR  >= 40)
if(VAR  == 20)
if(VAR [VAR] <= VAR)
if(VAR  == NULL)
if(VAR [VAR] == 20)
if(VAR [VAR] >= 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] == 30)
if(VAR [VAR] != 20)
if(VAR [VAR] >= 30)
if(VAR  <= NULL)
if(VAR  == 20)
if(VAR  == 30)
if(VAR  <= 20)
if(VAR  <= 40)
if(VAR  >= 30)
if(VAR  >= VAR)
if(VAR  == 30)
if(VAR [VAR] == 40)
if(VAR [VAR] != 20)
if(VAR  == 20)
if(VAR [VAR] >= 10)
if(VAR  <= 20)
if(VAR  >= 20)
if(VAR [VAR] != 20)
if(VAR  <= 20)
if(VAR  >= VAR)
if(VAR  <= 10)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= 40)
if(VAR  != 20)
if(VAR  != 30)
if(VAR  == 20)
if(VAR  <= 20)
if(VAR  != NULL)
if(VAR [VAR] == NULL)
if(VAR  >= 30)
if(VAR [VAR] == 20)
if(VAR [VAR] >= 30)
if(VAR [VAR] == 30)
if(VAR [VAR] >= 20)
if(VAR  >= VAR)
if(VAR  == 40)
if(VAR [VAR] == NULL)
if(VAR [VAR] >= 10)
if(VAR  >= 40)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= 40)
if(VAR [VAR] == 40)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= 20)
if(VAR [VAR] != 20)
if(VAR [VAR] != 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != 20)
if(VAR [VAR] <= NULL)
if(VAR [VAR] <= 20)
if(VAR  >= 30)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= 20)
if(VAR  <= 20)
if(VAR [VAR] != 20)
if(VAR  >= 20)
if(VAR [VAR] <= VAR)
if(VAR  >= 40)
if(VAR [VAR] <= 10)
if(VAR [VAR] != 40)
if(VAR [VAR] != 30)
if(VAR [VAR] != 40)
if(VAR [VAR] >= 20)
if(VAR  != 20)
if(VAR [VAR] >= VAR)
if(VAR  != VAR)
if(VAR  >= 40)
if(VAR [VAR] != 10)
if(VAR [VAR] >= 30)
if(VAR  != 10)
if(VAR  >= 10)
if(VAR  != 40)
if(VAR  <= 40)
if(VAR  != NULL)
if(VAR  == VAR)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= VAR)
if(VAR  != 20)
if(VAR [VAR] == 40)
if(VAR  != VAR)
if(VAR [VAR] <= 40)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != 30)
if(VAR  <= 30)
if(VAR  != 20)
if(VAR  >= 10)
if(VAR  == 40)
if(VAR [VAR] <= 20)
if(VAR  <= VAR)
if(VAR [VAR] != 10)
if(VAR [VAR] == 20)
if(VAR [VAR] == 10)
if(VAR [VAR] != 40)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= 10)
if(VAR  <= 10)
if(VAR  <= 40)
if(VAR [VAR] >= 30)
if(VAR  <= 30)
if(VAR [VAR] <= 30)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= VAR)
if(VAR  != NULL)
if(VAR  == 40)
if(VAR [VAR] != 30)
if(VAR  != 20)
if(VAR  <= NULL)
if(VAR  == 30)
if(VAR  >= 20)
if(VAR  <= NULL)
if(VAR  <= 40)
if(VAR  <= 20)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= NULL)
if(VAR  <= 30)
if(VAR [VAR] != 40)
if(VAR [VAR] == VAR)
if(VAR  == VAR)
if(VAR [VAR] <= VAR)
if(VAR  != 30)
if(VAR  == NULL)
if(VAR [VAR] != 40)
if(VAR  != NULL)
if(VAR  <= 40)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != 30)
if(VAR [VAR] == 10)
if(VAR  <= 10)
if(VAR  != NULL)
if(VAR  >= 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= VAR)
if(VAR  != 10)
if(VAR  == 10)
if(VAR  <= 40)
if(VAR [VAR] == 10)
if(VAR  != VAR)
if(VAR  >= 40)
if(VAR [VAR] >= 20)
if(VAR [VAR] == NULL)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= 40)
if(VAR  >= NULL)
if(VAR [VAR] != 40)
if(VAR  >= 20)
if(VAR [VAR] != 10)
if(VAR [VAR] != 20)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != 10)
if(VAR [VAR] != 30)
if(VAR  != 10)
if(VAR [VAR] != 10)
if(VAR [VAR] != 10)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] >= 30)
if(VAR  == 20)
if(VAR [VAR] == NULL)
if(VAR  <= 10)
if(VAR  != VAR)
if(VAR  <= 30)
if(VAR [VAR] >= 10)
if(VAR  != 20)
if(VAR [VAR] >= NULL)
if(VAR  >= 20)
if(VAR [VAR] != 40)
if(VAR  >= VAR)
if(VAR  <= 40)
if(VAR  >= 40)
if(VAR  >= 40)
if(VAR  == NULL)
if(VAR [VAR] >= 10)
if(VAR [VAR] != 40)
if(VAR  >= 20)
if(VAR [VAR] <= 30)
if(VAR [VAR] >= 40)
if(VAR  == 20)
if(VAR [VAR] != VAR)
if(VAR  != 40)
if(VAR [VAR] == 20)
if(VAR [VAR] == 30)
if(VAR  >= 20)
if(VAR [VAR] >= 30)
if(VAR  == 10)
if(VAR  == VAR)
if(VAR [VAR] != NULL)
if(VAR  == NULL)
if(VAR  >= 30)
if(VAR [VAR] != VAR)
if(VAR  != 40)
if(VAR [VAR] == 10)
if(VAR  != 10)
if(VAR [VAR] != 20)
if(VAR  <= 20)
if(VAR  <= 30)
if(VAR  <= VAR)
if(VAR  <= 40)
if(VAR [VAR] == 40)
if(VAR [VAR] != 10)
if(VAR  <= 30)
if(VAR  <= 10)
if(VAR [VAR] != 20)
if(VAR  <= 40)
if(VAR [VAR] <= 40)
if(VAR  != 10)
if(VAR  == VAR)
if(VAR  == VAR)
if(VAR  >= 30)
if(VAR  >= 20)
if(VAR  != VAR)
if(VAR  <= NULL)
if(VAR [VAR] <= VAR)
if(VAR [VAR] != NULL)
if(VAR  != VAR)
if(VAR  <= 40)
if(VAR  == 30)
if(VAR [VAR] >= NULL)
if(VAR  <= 40)
if(VAR  >= 10)
if(VAR  == NULL)
if(VAR [VAR] >= 20)
if(VAR  <= NULL)
if(VAR  == 30)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != NULL)
if(VAR  == 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= VAR)
if(VAR [VAR] <= NULL)
if(VAR  != 40)
if(VAR [VAR] == 40)
if(VAR  <= VAR)
if(VAR  <= 30)
if(VAR [VAR] == 30)
if(VAR [VAR] <= 40)
if(VAR [VAR] <= 20)
if(VAR  >= NULL)
if(VAR  == 20)
if(VAR [VAR] != 10)
if(VAR  <= 40)
if(VAR  == 40)
if(VAR  >= 40)
if(VAR  == 30)
if(VAR  != NULL)
if(VAR  <= 30)
if(VAR [VAR] != NULL)
if(VAR [VAR] == 10)
if(VAR  <= 20)
if(VAR [VAR] == NULL)
if(VAR  == 10)
if(VAR  >= 20)
if(VAR  == 10)
if(VAR [VAR] <= 40)
if(VAR  != 40)
if(VAR  <= 10)
if(VAR  <= NULL)
if(VAR [VAR] == 20)
if(VAR [VAR] == 10)
if(VAR  != 10)
if(VAR [VAR] <= VAR)
if(VAR  != 10)
if(VAR [VAR] <= 40)
if(VAR  >= 20)
if(VAR [VAR] != 10)
if(VAR  >= 20)
if(VAR [VAR] >= 20)
if(VAR  != VAR)
if(VAR [VAR] != VAR)
if(VAR [VAR] != 10)
if(VAR  != 20)
if(VAR [VAR] != 20)
if(VAR [VAR] <= NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != VAR)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == NULL)
if(VAR [VAR] <= 10)
if(VAR  != 20)
if(VAR  == 20)
if(VAR  <= 30)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] >= 40)
if(VAR [VAR] != 10)
if(VAR  <= 40)
if(VAR  >= 20)
if(VAR  == 30)
if(VAR [VAR] != 30)
if(VAR [VAR] >= 20)
if(VAR  >= 30)
if(VAR  >= 20)
if(VAR [VAR] != 20)
if(VAR  >= VAR)
if(VAR  <= 20)
if(VAR  == 30)
if(VAR  != 30)
if(VAR [VAR] != 40)
if(VAR  == 40)
if(VAR  <= VAR)
if(VAR  != VAR)
if(VAR  == NULL)
if(VAR [VAR] <= 30)
if(VAR [VAR] == 40)
if(VAR [VAR] != 20)
if(VAR  == 40)
if(VAR  <= 30)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= 20)
if(VAR  == 10)
if(VAR  != VAR)
if(VAR [VAR] <= VAR)
if(VAR [VAR] == NULL)
if(VAR [VAR] <= NULL)
if(VAR  == 10)
if(VAR  == NULL)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= NULL)
if(VAR  == NULL)
if(VAR  != 40)
if(VAR [VAR] >= 10)
if(VAR  >= 10)
if(VAR  != 10)
if(VAR  >= 20)
if(VAR [VAR] <= 30)
if(VAR  != 20)
if(VAR [VAR] <= 10)
if(VAR  == VAR)
if(VAR [VAR] >= 10)
if(VAR  >= 30)
if(VAR [VAR] == 40)
if(VAR [VAR] == 40)
if(VAR  <= VAR)
if(VAR  >= VAR)
if(VAR  >= 40)
if(VAR [VAR] >= VAR)
if(VAR  >= NULL)
if(VAR [VAR] != 40)
if(VAR  >= 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] == NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] == NULL)
if(VAR  != VAR)
if(VAR [VAR] >= 10)
if(VAR  >= 20)
if(VAR  <= 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] != 20)
if(VAR [VAR] != VAR)
if(VAR [VAR] != 10)
if(VAR [VAR] == 10)
if(VAR  >= 30)
if(VAR  != 30)
if(VAR [VAR] == 30)
if(VAR [VAR] != NULL)
if(VAR [VAR] >= NULL)
if(VAR  >= 40)
if(VAR [VAR] >= 20)
if(VAR [VAR] != VAR)
if(VAR  <= 10)
if(VAR  <= 20)
if(VAR [VAR] == 40)
if(VAR [VAR] == NULL)
if(VAR  <= 10)
if(VAR [VAR] == NULL)
if(VAR  >= 20)
if(VAR  <= VAR)
if(VAR  >= 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] != NULL)
if(VAR  <= NULL)
if(VAR  == NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] != NULL)
if(VAR  <= 10)
if(VAR  == 30)
if(VAR  >= 20)
if(VAR [VAR] <= VAR)
if(VAR  >= VAR)
if(VAR  <= NULL)
if(VAR [VAR] == 10)
if(VAR [VAR] >= 20)
if(VAR  == NULL)
if(VAR [VAR] != 10)
if(VAR  != 10)
if(VAR [VAR] != 30)
if(VAR  == 30)
if(VAR  >= VAR)
if(VAR  == 30)
if(VAR [VAR] != VAR)
if(VAR  == VAR)
if(VAR  <= VAR)
if(VAR  <= VAR)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= 20)
if(VAR  == 10)
if(VAR [VAR] == VAR)
if(VAR [VAR] != 30)
if(VAR [VAR] >= 40)
if(VAR  == 10)
if(VAR  == 40)
if(VAR [VAR] <= NULL)
if(VAR  == 10)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != 30)
if(VAR [VAR] != 30)
if(VAR [VAR] >= 40)
if(VAR [VAR] == 30)
if(VAR  == NULL)
if(VAR  <= 10)
if(VAR  == 30)
if(VAR [VAR] == 20)
if(VAR [VAR] == 10)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= 40)
if(VAR  >= 40)
if(VAR  >= 40)
if(VAR [VAR] <= NULL)
if(VAR  != VAR)
if(VAR [VAR] <= 20)
if(VAR  == 20)
if(VAR [VAR] <= VAR)
if(VAR  >= 10)
if(VAR  <= 10)
if(VAR  <= VAR)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != 30)
if(VAR [VAR] <= 10)
if(VAR  == 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] <= 40)
if(VAR  != 10)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= 10)
if(VAR  != NULL)
if(VAR [VAR] >= NULL)
if(VAR  >= 40)
if(VAR [VAR] >= 20)
if(VAR  >= 20)
if(VAR  != VAR)
if(VAR  == NULL)
if(VAR  == NULL)
if(VAR  <= NULL)
if(VAR [VAR] == 10)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= VAR)
if(VAR  != 30)
if(VAR  == 40)
if(VAR  != NULL)
if(VAR  <= 30)
if(VAR [VAR] != 20)
if(VAR  == 30)
if(VAR [VAR] >= NULL)
if(VAR  <= 40)
if(VAR [VAR] != 40)
if(VAR [VAR] == 10)
if(VAR [VAR] == 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= 40)
if(VAR [VAR] == 40)
if(VAR  == 10)
if(VAR  != 10)
if(VAR  >= 40)
if(VAR [VAR] == 40)
if(VAR  <= 20)
if(VAR [VAR] <= 30)
if(VAR [VAR] == VAR)
if(VAR  >= 20)
if(VAR [VAR] == VAR)
if(VAR  != 40)
if(VAR  == VAR)
if(VAR [VAR] != 20)
if(VAR [VAR] == NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] != VAR)
if(VAR  != NULL)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= 30)
if(VAR  != VAR)
if(VAR  >= VAR)
if(VAR [VAR] != 20)
if(VAR [VAR] <= VAR)
if(VAR  == 30)
if(VAR [VAR] == 30)
if(VAR  >= VAR)
if(VAR  >= 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != 10)
if(VAR [VAR] != 10)
if(VAR  >= 40)
if(VAR [VAR] != 20)
if(VAR  != 30)
if(VAR  == NULL)
if(VAR  != 40)
if(VAR [VAR] <= 30)
if(VAR  == 10)
if(VAR [VAR] == 30)
if(VAR [VAR] == NULL)
if(VAR  == NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] == 10)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= 40)
if(VAR  <= 30)
if(VAR [VAR] != 30)
if(VAR [VAR] <= 40)
if(VAR  >= 10)
if(VAR  <= 20)
if(VAR  >= 20)
if(VAR  >= 40)
if(VAR [VAR] == 10)
if(VAR [VAR] != 30)
if(VAR  >= VAR)
if(VAR [VAR] <= 30)
if(VAR  != 40)
if(VAR [VAR] != 40)
if(VAR  >= 30)
if(VAR  != VAR)
if(VAR  == 30)
if(VAR  >= VAR)
if(VAR [VAR] >= 40)
if(VAR [VAR] == 10)
if(VAR [VAR] == 30)
if(VAR [VAR] != 20)
if(VAR [VAR] == 40)
if(VAR  == 10)
if(VAR  >= 10)
if(VAR  == 10)
if(VAR  <= VAR)
if(VAR [VAR] != 30)
if(VAR  >= NULL)
if(VAR [VAR] >= 40)
if(VAR  == NULL)
if(VAR [VAR] == 20)
if(VAR  <= 20)
if(VAR  >= 30)
if(VAR  >= 40)
if(VAR  == 20)
if(VAR  <= 10)
if(VAR  >= 10)
if(VAR  <= NULL)
if(VAR [VAR] >= 20)
if(VAR [VAR] != 40)
if(VAR  == 20)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= 20)
if(VAR  == 20)
if(VAR  >= VAR)
if(VAR [VAR] <= NULL)
if(VAR  <= 40)
if(VAR [VAR] <= 30)
if(VAR  <= NULL)
if(VAR [VAR] <= 10)
if(VAR  <= 20)
if(VAR [VAR] >= 30)
if(VAR [VAR] >= VAR)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= 20)
if(VAR  != NULL)
if(VAR  <= 30)
if(VAR  == 10)
if(VAR  >= 20)
if(VAR  >= 40)
if(VAR [VAR] <= NULL)
if(VAR  != 40)
if(VAR  <= NULL)
if(VAR  <= 30)
if(VAR  <= 30)
if(VAR [VAR] <= NULL)
if(VAR  <= 30)
if(VAR  != VAR)
if(VAR [VAR] != VAR)
if(VAR  <= 30)
if(VAR [VAR] >= 30)
if(VAR [VAR] == 10)
if(VAR  != 20)
if(VAR [VAR] == 40)
if(VAR [VAR] == 20)
if(VAR  >= 40)
if(VAR [VAR] <= VAR)
if(VAR  >= 40)
if(VAR  != 20)
if(VAR  == VAR)
if(VAR [VAR] != NULL)
if(VAR  != NULL)
if(VAR [VAR] >= 20)
if(VAR [VAR] == 20)
if(VAR [VAR] >= 30)
if(VAR  >= NULL)
if(VAR [VAR] >= 20)
if(VAR [VAR] == 40)
if(VAR  != VAR)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != NULL)
if(VAR [VAR] != 30)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= 40)
if(VAR  != 30)
if(VAR  != VAR)
if(VAR  <= 30)
if(VAR  >= VAR)
if(VAR  != 40)
if(VAR  != NULL)
if(VAR [VAR] != 10)
if(VAR  >= 10)
if(VAR [VAR] <= 40)
if(VAR [VAR] == 40)
if(VAR [VAR] == 20)
if(VAR  <= 10)
if(VAR  <= VAR)
if(VAR [VAR] == 10)
if(VAR  <= NULL)
if(VAR [VAR] != 30)
if(VAR  <= NULL)
if(VAR  <= VAR)
if(VAR [VAR] == 40)
if(VAR  != 30)
if(VAR [VAR] <= NULL)
if(VAR  != 40)
if(VAR [VAR] >= 10)
if(VAR  <= NULL)
if(VAR  != 20)
if(VAR  >= 20)
if(VAR  >= 40)
if(VAR  <= 30)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= 40)
if(VAR  <= NULL)
if(VAR [VAR] == 10)
if(VAR [VAR] >= 10)
if(VAR  <= 40)
if(VAR [VAR] <= NULL)
if(VAR  >= NULL)
if(VAR [VAR] <= 20)
if(VAR  <= VAR)
if(VAR [VAR] <= 30)
if(VAR  != NULL)
if(VAR  != 30)
if(VAR [VAR] != 10)
if(VAR [VAR] >= 30)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != VAR)
if(VAR [VAR] == 10)
if(VAR [VAR] <= VAR)
if(VAR  <= 20)
if(VAR [VAR] != 40)
if(VAR  <= VAR)
if(VAR  == VAR)
if(VAR  == NULL)
if(VAR  != 40)
if(VAR [VAR] <= 20)
if(VAR  >= 20)
if(VAR [VAR] == 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= VAR)
if(VAR  <= 40)
if(VAR [VAR] >= 40)
if(VAR  == 10)
if(VAR  >= 20)
if(VAR [VAR] != 20)
if(VAR [VAR] <= 20)
if(VAR  != 30)
if(VAR [VAR] <= NULL)
if(VAR  >= 20)
if(VAR [VAR] == VAR)
if(VAR  >= 30)
if(VAR [VAR] != 30)
if(VAR  <= VAR)
if(VAR  != 10)
if(VAR  >= 40)
if(VAR  != 40)
if(VAR  <= VAR)
if(VAR [VAR] <= 10)
if(VAR  == 30)
if(VAR  == VAR)
if(VAR [VAR] != 10)
if(VAR  >= VAR)
if(VAR  >= 40)
if(VAR  == NULL)
if(VAR  >= 40)
if(VAR [VAR] >= 30)
if(VAR [VAR] >= VAR)
if(VAR  != 30)
if(VAR [VAR] != 10)
if(VAR [VAR] != 20)
if(VAR  == 10)
if(VAR [VAR] <= VAR)
if(VAR  >= VAR)
if(VAR  <= 40)
if(VAR [VAR] <= 30)
if(VAR [VAR] == 40)
if(VAR  == 10)
if(VAR  != 20)
if(VAR [VAR] == VAR)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= 20)
if(VAR [VAR] != 10)
if(VAR [VAR] == 20)
if(VAR [VAR] != 30)
if(VAR [VAR] <= NULL)
if(VAR  >= 10)
if(VAR [VAR] >= 30)
if(VAR  <= VAR)
if(VAR [VAR] >= 40)
if(VAR  >= 30)
if(VAR [VAR] <= 40)
if(VAR  != NULL)
if(VAR [VAR] >= 10)
if(VAR [VAR] == 10)
if(VAR  == NULL)
if(VAR  <= 40)
if(VAR [VAR] == 30)
if(VAR [VAR] == 20)
if(VAR [VAR] == VAR)
if(VAR [VAR] == 30)
if(VAR [VAR] != 40)
if(VAR [VAR] != 40)
if(VAR  != VAR)
if(VAR  >= 40)
if(VAR  >= 40)
if(VAR  <= VAR)
if(VAR [VAR] == 40)
if(VAR  == VAR)
if(VAR  <= 30)
if(VAR [VAR] == 40)
if(VAR [VAR] == 30)
if(VAR [VAR] <= VAR)
if(VAR  != 20)
if(VAR [VAR] != NULL)
if(VAR [VAR] != 30)
if(VAR [VAR] == VAR)
if(VAR  <= 30)
if(VAR [VAR] >= 10)
if(VAR  <= NULL)
if(VAR [VAR] <= 40)
if(VAR [VAR] >= 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] >= 20)
if(VAR  != 40)
if(VAR [VAR] >= 10)
if(VAR  == VAR)
if(VAR [VAR] <= VAR)
if(VAR [VAR] == 40)
if(VAR  == 40)
if(VAR  == 30)
if(VAR [VAR] != 30)
if(VAR  != VAR)
if(VAR  != 30)
if(VAR  <= 20)
if(VAR  >= 40)
if(VAR [VAR] >= 40)
if(VAR  <= 10)
if(VAR [VAR] <= 40)
if(VAR [VAR] != 30)
if(VAR [VAR] >= NULL)
if(VAR  >= NULL)
if(VAR  >= 10)
if(VAR [VAR] != VAR)
if(VAR [VAR] != VAR)
if(VAR  != 40)
if(VAR [VAR] != VAR)
if(VAR [VAR] <= 30)
if(VAR [VAR] == 40)
if(VAR  != NULL)
if(VAR [VAR] != 10)
if(VAR  == 40)
if(VAR  != 10)
if(VAR  <= VAR)
if(VAR  != VAR)
if(VAR [VAR] == 20)
if(VAR  <= NULL)
if(VAR  >= NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= VAR)
if(VAR  != 10)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= NULL)
if(VAR  == VAR)
if(VAR [VAR] != 20)
if(VAR [VAR] <= NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] == 20)
if(VAR  >= 20)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= VAR)
if(VAR  <= 20)
if(VAR  <= NULL)
if(VAR  <= 10)
if(VAR  <= 20)
if(VAR [VAR] == 20)
if(VAR [VAR] >= NULL)
if(VAR  <= 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= NULL)
if(VAR  == 40)
if(VAR [VAR] <= VAR)
if(VAR  != 10)
if(VAR [VAR] != 40)
if(VAR  == VAR)
if(VAR  == 20)
if(VAR  >= 30)
if(VAR  >= 20)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 20)
if(VAR  == NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 30)
if(VAR  != 10)
if(VAR  == 20)
if(VAR  >= 40)
if(VAR [VAR] <= 40)
if(VAR  <= 20)
if(VAR [VAR] != 20)
if(VAR  == NULL)
if(VAR  >= VAR)
if(VAR  <= 10)
if(VAR [VAR] != 10)
if(VAR  == 30)
if(VAR  <= NULL)
if(VAR  != 40)
if(VAR  == 40)
if(VAR  == VAR)
if(VAR [VAR] != VAR)
if(VAR  != 40)
if(VAR  == 40)
if(VAR  != VAR)
if(VAR  != 40)
if(VAR [VAR] == 10)
if(VAR  <= NULL)
if(VAR [VAR] == 20)
if(VAR  == VAR)
if(VAR [VAR] >= 20)
if(VAR  >= VAR)
if(VAR  != 40)
if(VAR  <= 30)
if(VAR  != VAR)
if(VAR [VAR] >= 20)
if(VAR  <= 40)
if(VAR [VAR] <= 30)
if(VAR  != 20)
if(VAR  <= NULL)
if(VAR [VAR] <= VAR)
if(VAR  != 10)
if(VAR [VAR] == VAR)
if(VAR [VAR] <= 30)
if(VAR  >= NULL)
if(VAR  == VAR)
if(VAR  >= 20)
if(VAR  >= NULL)
if(VAR  != 20)
if(VAR  != 10)
if(VAR  <= 30)
if(VAR [VAR] == VAR)
if(VAR [VAR] == 40)
if(VAR [VAR] != 40)
if(VAR  != VAR)
if(VAR [VAR] <= 20)
if(VAR  != 40)
if(VAR  >= 10)
if(VAR  <= NULL)
if(VAR [VAR] <= 10)
if(VAR [VAR] == 30)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] == VAR)
if(VAR [VAR] != VAR)
if(VAR  <= 40)
if(VAR  >= NULL)
if(VAR  == 30)
if(VAR  != VAR)
if(VAR [VAR] >= 10)
if(VAR  >= 30)
if(VAR [VAR] >= NULL)
if(VAR  <= NULL)
if(VAR  == VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] <= NULL)
if(VAR  == 10)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= 30)
if(VAR [VAR] != 40)
if(VAR [VAR] != 40)
if(VAR  >= NULL)
if(VAR  <= 20)
if(VAR  >= VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] >= NULL)
if(VAR  <= 30)
if(VAR  >= 10)
if(VAR  != 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] == 40)
if(VAR [VAR] >= 40)
if(VAR  <= 30)
if(VAR  == NULL)
if(VAR [VAR] >= NULL)
if(VAR  == NULL)
if(VAR  >= 30)
if(VAR [VAR] >= 40)
if(VAR  != VAR)
if(VAR [VAR] >= 40)
if(VAR  == 20)
if(VAR  <= NULL)
if(VAR  >= NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] == 30)
if(VAR [VAR] <= 20)
if(VAR  != VAR)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != 40)
if(VAR  <= 30)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 40)
if(VAR  <= 40)
if(VAR  <= 20)
if(VAR [VAR] == 40)
if(VAR  <= 10)
if(VAR [VAR] >= NULL)
if(VAR  >= 10)
if(VAR [VAR] <= 40)
if(VAR  >= 40)
if(VAR [VAR] == 10)
if(VAR [VAR] == 30)
if(VAR  == NULL)
if(VAR  != VAR)
if(VAR  != 20)
if(VAR [VAR] >= NULL)
if(VAR  <= 40)
if(VAR [VAR] == 40)
if(VAR [VAR] >= 20)
if(VAR [VAR] == 40)
if(VAR [VAR] != VAR)
if(VAR [VAR] != 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= 10)
if(VAR [VAR] != NULL)
if(VAR [VAR] != 30)
if(VAR [VAR] <= 20)
if(VAR  <= NULL)
if(VAR [VAR] != VAR)
if(VAR  == VAR)
if(VAR  != 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= 20)
if(VAR  == 30)
if(VAR  != 30)
if(VAR [VAR] == 20)
if(VAR [VAR] != NULL)
if(VAR  >= NULL)
if(VAR [VAR] <= NULL)
if(VAR  != VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] >= VAR)
if(VAR  == NULL)
if(VAR  == 30)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 30)
if(VAR  <= 40)
if(VAR  >= 10)
if(VAR [VAR] != VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] <= VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= 40)
if(VAR  == 10)
if(VAR [VAR] != 20)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= 20)
if(VAR  != NULL)
if(VAR  == NULL)
if(VAR [VAR] != 10)
if(VAR [VAR] == VAR)
if(VAR [VAR] == NULL)
if(VAR  != 20)
if(VAR  == 10)
if(VAR [VAR] != VAR)
if(VAR [VAR] == VAR)
if(VAR [VAR] != 20)
if(VAR [VAR] == 20)
if(VAR  != 40)
if(VAR  <= VAR)
if(VAR  <= VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= 40)
if(VAR  >= 30)
if(VAR [VAR] != 20)
if(VAR  <= VAR)
if(VAR [VAR] <= 40)
if(VAR  <= 20)
if(VAR  <= VAR)
if(VAR [VAR] == 10)
if(VAR  >= 20)
if(VAR  >= 20)
if(VAR [VAR] == 10)
if(VAR  != NULL)
if(VAR  != VAR)
if(VAR  <= 10)
if(VAR  >= 10)
if(VAR [VAR] != 20)
if(VAR  >= 40)
if(VAR  == 20)
if(VAR [VAR] == 30)
if(VAR [VAR] >= NULL)
if(VAR  <= NULL)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != 40)
if(VAR [VAR] <= 10)
if(VAR [VAR] >= 40)
if(VAR  <= NULL)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= 20)
if(VAR  != 30)
if(VAR [VAR] >= 20)
if(VAR  >= 40)
if(VAR  >= 30)
if(VAR [VAR] <= 30)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= VAR)
if(VAR [VAR] <= 10)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= 40)
if(VAR  <= NULL)
if(VAR [VAR] >= VAR)
if(VAR [VAR] == 30)
if(VAR  <= 20)
if(VAR  <= NULL)
if(VAR [VAR] != NULL)
if(VAR [VAR] == 30)
if(VAR  != 10)
if(VAR  != 40)
if(VAR [VAR] != VAR)
if(VAR [VAR] == NULL)
if(VAR [VAR] >= 20)
if(VAR  != 10)
if(VAR [VAR] == 10)
if(VAR [VAR] != 20)
if(VAR [VAR] >= 20)
if(VAR  == NULL)
if(VAR  == NULL)
if(VAR  >= 20)
if(VAR [VAR] >= 10)
if(VAR [VAR] != 40)
if(VAR [VAR] != VAR)
if(VAR  != 30)
if(VAR  >= 30)
if(VAR  == NULL)
if(VAR  <= NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] == VAR)
if(VAR [VAR] != NULL)
if(VAR [VAR] == 40)
if(VAR  >= 20)
if(VAR  <= NULL)
if(VAR [VAR] <= 10)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= 20)
if(VAR  >= 30)
if(VAR  == 10)
if(VAR  == 10)
if(VAR  >= 30)
if(VAR [VAR] <= 10)
if(VAR  <= NULL)
if(VAR [VAR] >= 20)
if(VAR [VAR] != 40)
if(VAR [VAR] != 40)
if(VAR [VAR] != 30)
if(VAR  != VAR)
if(VAR  != 30)
if(VAR [VAR] <= NULL)
if(VAR [VAR] <= 10)
if(VAR [VAR] != 20)
if(VAR [VAR] != 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] != VAR)
if(VAR [VAR] >= 40)
if(VAR [VAR] == 20)
if(VAR [VAR] == 40)
if(VAR  != NULL)
if(VAR [VAR] <= 20)
if(VAR [VAR] == NULL)
if(VAR  <= 10)
if(VAR [VAR] == 20)
if(VAR  >= 30)
if(VAR [VAR] == 10)
if(VAR [VAR] <= 10)
if(VAR  == 40)
if(VAR [VAR] >= VAR)
if(VAR  >= VAR)
if(VAR [VAR] == 40)
if(VAR  == VAR)
if(VAR [VAR] >= 30)
if(VAR  != 40)
if(VAR [VAR] <= 30)
if(VAR [VAR] <= 20)
if(VAR [VAR] == 10)
if(VAR [VAR] >= NULL)
if(VAR  >= 30)
if(VAR [VAR] >= VAR)
if(VAR  == NULL)
if(VAR [VAR] <= VAR)
if(VAR [VAR] <= NULL)
if(VAR  <= VAR)
if(VAR [VAR] != 30)
if(VAR [VAR] >= 10)
if(VAR  <= NULL)
if(VAR [VAR] == 30)
if(VAR  <= 40)
if(VAR  != NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] <= 20)
if(VAR  != 40)
if(VAR [VAR] == 40)
if(VAR [VAR] == NULL)
if(VAR  == 30)
if(VAR [VAR] != 10)
if(VAR [VAR] != VAR)
if(VAR  == NULL)
if(VAR  <= 40)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= 20)
if(VAR [VAR] != VAR)
if(VAR  == 30)
if(VAR [VAR] <= NULL)
if(VAR  != 10)
if(VAR [VAR] >= 10)
if(VAR [VAR] == 30)
if(VAR  <= NULL)
if(VAR  != 30)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != 40)
if(VAR  >= 30)
if(VAR  >= NULL)
if(VAR [VAR] <= VAR)
if(VAR  <= VAR)
if(VAR [VAR] == 30)
if(VAR  != 40)
if(VAR [VAR] != 40)
if(VAR [VAR] != NULL)
if(VAR [VAR] != VAR)
if(VAR [VAR] != 30)
if(VAR [VAR] <= VAR)
if(VAR [VAR] == NULL)
if(VAR  == 10)
if(VAR  != VAR)
if(VAR  >= 40)
if(VAR [VAR] <= VAR)
if(VAR [VAR] == 10)
if(VAR [VAR] <= 10)
if(VAR [VAR] != 20)
if(VAR  >= 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= 40)
if(VAR [VAR] == 30)
if(VAR  <= 40)
if(VAR  == NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] <= NULL)
if(VAR  >= 40)
if(VAR  != 10)
if(VAR  == 30)
if(VAR [VAR] <= 10)
if(VAR [VAR] >= 10)
if(VAR [VAR] == 10)
if(VAR  != VAR)
if(VAR  != 20)
if(VAR  <= VAR)
if(VAR [VAR] >= NULL)
if(VAR  <= NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 10)
if(VAR [VAR] != 10)
if(VAR [VAR] == 20)
if(VAR  == 40)
if(VAR [VAR] == 30)
if(VAR  <= 10)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= 30)
if(VAR [VAR] != NULL)
if(VAR  != NULL)
if(VAR [VAR] == 20)
if(VAR  >= 40)
if(VAR [VAR] <= NULL)
if(VAR  >= NULL)
if(VAR [VAR] >= 10)
if(VAR [VAR] == 40)
if(VAR [VAR] <= 10)
if(VAR [VAR] <= NULL)
if(VAR  != 20)
if(VAR  != VAR)
if(VAR  != 30)
if(VAR  != 40)
if(VAR  >= VAR)
if(VAR  >= 20)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= 40)
if(VAR  <= VAR)
if(VAR  >= VAR)
if(VAR  == 10)
if(VAR  >= 10)
if(VAR  != 40)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 10)
if(VAR [VAR] == 20)
if(VAR  <= 20)
if(VAR [VAR] == 20)
if(VAR  == 30)
if(VAR  == VAR)
if(VAR  <= 20)
if(VAR [VAR] <= NULL)
if(VAR [VAR] >= 10)
if(VAR  <= 10)
if(VAR  == 30)
if(VAR [VAR] >= 40)
if(VAR [VAR] <= 20)
if(VAR  >= 10)
if(VAR [VAR] <= 30)
if(VAR  != 40)
if(VAR  <= 20)
if(VAR  >= NULL)
if(VAR [VAR] != VAR)
if(VAR [VAR] != 10)
if(VAR  <= 30)
if(VAR [VAR] != 30)
if(VAR  == 20)
if(VAR [VAR] >= VAR)
if(VAR  != 10)
if(VAR [VAR] >= 40)
if(VAR  <= 20)
if(VAR [VAR] == 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= 40)
if(VAR  >= 20)
if(VAR  != 10)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != NULL)
if(VAR  != 20)
if(VAR  >= 30)
if(VAR  == NULL)
if(VAR [VAR] == VAR)
if(VAR  >= 20)
if(VAR  <= VAR)
if(VAR  == NULL)
if(VAR  != NULL)
if(VAR [VAR] == NULL)
if(VAR  == NULL)
if(VAR  != 10)
if(VAR  != NULL)
if(VAR [VAR] <= 40)
if(VAR  == 40)
if(VAR  <= VAR)
if(VAR [VAR] != VAR)
if(VAR  <= 20)
if(VAR [VAR] != 30)
if(VAR  <= VAR)
if(VAR [VAR] == 20)
if(VAR [VAR] <= 20)
if(VAR [VAR] != 20)
if(VAR [VAR] != NULL)
if(VAR  != NULL)
if(VAR [VAR] <= 30)
if(VAR  != 30)
if(VAR  != 20)
if(VAR [VAR] == 40)
if(VAR  != VAR)
if(VAR  != 30)
if(VAR [VAR] == 20)
if(VAR  != VAR)
if(VAR [VAR] != 20)
if(VAR  != 20)
if(VAR [VAR] == NULL)
if(VAR  == 20)
if(VAR [VAR] >= 10)
if(VAR [VAR] == 10)
if(VAR [VAR] >= 30)
if(VAR [VAR] != NULL)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 10)
if(VAR  <= VAR)
if(VAR  != NULL)
if(VAR  != 30)
if(VAR  <= 40)
if(VAR  == 10)
if(VAR [VAR] <= NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] == 30)
if(VAR  != 20)
if(VAR [VAR] >= NULL)
if(VAR  <= 10)
if(VAR  >= NULL)
if(VAR  <= VAR)
if(VAR  != 20)
if(VAR [VAR] != 30)
if(VAR  != 30)
if(VAR  >= 40)
if(VAR  >= 30)
if(VAR  >= VAR)
if(VAR [VAR] >= 20)
if(VAR  >= NULL)
if(VAR [VAR] >= 10)
if(VAR  == VAR)
if(VAR  >= NULL)
if(VAR  != NULL)
if(VAR [VAR] <= 10)
if(VAR [VAR] != 20)
if(VAR [VAR] == 40)
if(VAR  == 20)
if(VAR  <= 20)
if(VAR [VAR] <= 10)
if(VAR  != 10)
if(VAR [VAR] != 30)
if(VAR  >= 40)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != 40)
if(VAR  >= 40)
if(VAR  != 10)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= 20)
if(VAR [VAR] != VAR)
if(VAR [VAR] == 30)
if(VAR [VAR] == 30)
if(VAR  != 20)
if(VAR [VAR] != 10)
if(VAR [VAR] >= 30)
if(VAR [VAR] == 10)
if(VAR  != 30)
if(VAR [VAR] >= 30)
if(VAR [VAR] == 20)
if(VAR  <= 30)
if(VAR [VAR] != 40)
if(VAR  == VAR)
if(VAR  == NULL)
if(VAR [VAR] >= 10)
if(VAR [VAR] <= 40)
if(VAR  != VAR)
if(VAR  >= 40)
if(VAR  == 20)
if(VAR  == 40)
if(VAR  != 10)
if(VAR [VAR] == NULL)
if(VAR [VAR] != 40)
if(VAR  != 20)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= 40)
if(VAR  != NULL)
if(VAR [VAR] >= 10)
if(VAR  == 30)
if(VAR  <= NULL)
if(VAR  >= 40)
if(VAR [VAR] <= 20)
if(VAR [VAR] != NULL)
if(VAR [VAR] == 10)
if(VAR [VAR] == VAR)
if(VAR  <= NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= 40)
if(VAR [VAR] != 10)
if(VAR  >= VAR)
if(VAR  == 20)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= VAR)
if(VAR  != 10)
if(VAR [VAR] == NULL)
if(VAR [VAR] <= 10)
if(VAR  == 30)
if(VAR [VAR] <= 40)
if(VAR  != 30)
if(VAR [VAR] <= 40)
if(VAR  == VAR)
if(VAR  != 40)
if(VAR [VAR] >= NULL)
if(VAR  == 40)
if(VAR  != NULL)
if(VAR  <= 40)
if(VAR [VAR] == 20)
if(VAR  != 30)
if(VAR [VAR] == 40)
if(VAR [VAR] == 40)
if(VAR  >= VAR)
if(VAR  >= NULL)
if(VAR [VAR] <= VAR)
if(VAR [VAR] != 10)
if(VAR [VAR] != NULL)
if(VAR  != 20)
if(VAR [VAR] <= NULL)
if(VAR  != VAR)
if(VAR [VAR] == 40)
if(VAR  == 30)
if(VAR [VAR] <= 40)
if(VAR  <= 20)
if(VAR [VAR] <= 20)
if(VAR [VAR] >= VAR)
if(VAR  <= 20)
if(VAR  == 40)
if(VAR [VAR] != 30)
if(VAR  <= 40)
if(VAR [VAR] >= NULL)
if(VAR  == 10)
if(VAR  >= VAR)
if(VAR [VAR] >= VAR)
if(VAR  != 40)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= 30)
if(VAR  == 20)
if(VAR  == 20)
if(VAR  != 20)
if(VAR [VAR] <= NULL)
if(VAR [VAR] >= 30)
if(VAR  != 30)
if(VAR  == 10)
if(VAR [VAR] >= NULL)
if(VAR [VAR] <= 40)
if(VAR  == VAR)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= 10)
if(VAR [VAR] == VAR)
if(VAR [VAR] >= NULL)
if(VAR [VAR] == 30)
if(VAR  >= 30)
if(VAR [VAR] <= 40)
if(VAR [VAR] != VAR)
if(VAR  == VAR)
if(VAR [VAR] <= 10)
if(VAR [VAR] == NULL)
if(VAR  == 10)
if(VAR  == NULL)
if(VAR  == 20)
if(VAR [VAR] >= VAR)
if(VAR  != NULL)
if(VAR  >= NULL)
if(VAR [VAR] >= 20)
if(VAR  <= 40)
if(VAR  >= NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] != NULL)
if(VAR [VAR] == VAR)
if(VAR  <= 10)
if(VAR [VAR] <= 20)
if(VAR  == 20)
if(VAR  >= 20)
if(VAR [VAR] != VAR)
if(VAR  <= 20)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= VAR)
if(VAR  != VAR)
if(VAR [VAR] >= 10)
if(VAR [VAR] >= 40)
if(VAR [VAR] != 20)
if(VAR  >= 40)
if(VAR [VAR] == VAR)
if(VAR [VAR] <= VAR)
if(VAR [VAR] == NULL)
if(VAR [VAR] <= 20)
if(VAR  != 20)
if(VAR [VAR] >= 10)
if(VAR  >= VAR)
if(VAR  == 20)
if(VAR [VAR] == 30)
if(VAR  == NULL)
if(VAR [VAR] <= 20)
if(VAR  <= 40)
if(VAR [VAR] == 30)
if(VAR [VAR] >= 20)
if(VAR  >= NULL)
if(VAR  != NULL)
if(VAR  <= 20)
if(VAR [VAR] != 10)
if(VAR  >= 30)
if(VAR [VAR] >= 20)
if(VAR  >= 20)
if(VAR [VAR] == 30)
if(VAR [VAR] != 40)
if(VAR  >= VAR)
if(VAR [VAR] <= 20)
if(VAR  <= NULL)
if(VAR  >= NULL)
if(VAR [VAR] >= 10)
if(VAR  <= VAR)
if(VAR  <= 20)
if(VAR [VAR] == 40)
if(VAR  != 30)
if(VAR [VAR] == 10)
if(VAR [VAR] >= 20)
if(VAR [VAR] >= 30)
if(VAR [VAR] == NULL)
if(VAR [VAR] == 30)
if(VAR [VAR] != NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] <= VAR)
if(VAR  == 10)
if(VAR [VAR] != 10)
if(VAR  <= 40)
if(VAR [VAR] <= VAR)
if(VAR  <= 40)
if(VAR  <= 30)
if(VAR [VAR] == 20)
if(VAR [VAR] != VAR)
if(VAR  == NULL)
if(VAR  >= 20)
if(VAR [VAR] >= 40)
if(VAR  >= 10)
if(VAR [VAR] >= 40)
if(VAR  == 30)
if(VAR  >= 20)
if(VAR [VAR] == 10)
if(VAR [VAR] <= VAR)
if(VAR [VAR] >= VAR)
if(VAR  <= NULL)
if(VAR [VAR] != NULL)
if(VAR [VAR] != VAR)
if(VAR  <= 10)
if(VAR [VAR] >= 40)
if(VAR  == 40)
if(VAR  <= 40)
if(VAR [VAR] >= 40)
if(VAR  <= 40)
if(VAR [VAR] != 10)
if(VAR [VAR] == 10)
if(VAR  == 20)
if(VAR  >= 40)
if(VAR [VAR] <= 10)
if(VAR [VAR] != VAR)
if(VAR  == 40)
if(VAR [VAR] != VAR)
if(VAR [VAR] >= VAR)
if(VAR  <= NULL)
if(VAR [VAR] >= NULL)
if(VAR  != NULL)
if(VAR  == 10)
if(VAR  != NULL)
if(VAR [VAR] >= NULL)
if(VAR [VAR] >= 30)
if(VAR [VAR] != 40)
if(VAR  >= NULL)
if(VAR  == 40)
if(VAR [VAR] != 40)
if(VAR  >= 40)
if(VAR [VAR] <= VAR)
if(VAR  >= 20)
if(VAR  >= VAR)
if(VAR [VAR] != 10)
if(VAR  <= NULL)
if(VAR  != 10)
if(VAR [VAR] >= 20)
if(VAR  >= 20)
if(VAR [VAR] <= 20)
if(VAR  >= 20)
if(VAR [VAR] == 20)
if(VAR  != 40)
if(VAR [VAR] == 20)
if(VAR  == 20)
if(VAR [VAR] >= 40)
if(VAR  <= 10)
if(VAR [VAR] != 40)
if(VAR [VAR] != 20)
if(VAR  != 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] == VAR)
if(VAR  <= 10)
if(VAR [VAR] <= VAR)
if(VAR  != NULL)
if(VAR  != 20)
if(VAR  == NULL)
if(VAR [VAR] >= 20)
if(VAR [VAR] <= 30)
if(VAR [VAR] != 40)
if(VAR [VAR] <= NULL)
if(VAR [VAR] <= NULL)
if(VAR [VAR] != NULL)
if(VAR [VAR] != 30)
if(VAR  <= NULL)
if(VAR  == 40)
if(VAR [VAR] == 10)
if(VAR [VAR] == 10)
if(VAR  == VAR)
if(VAR [VAR] <= NULL)
if(VAR [VAR] >= VAR)
if(VAR [VAR] != 40)
if(VAR  <= 30)
if(VAR [VAR] == 10)
if(VAR [VAR] == NULL)
if(VAR  == 20)
if(VAR [VAR] != 20)
if(VAR [VAR] == 10)
if(VAR  <= 40)
if(VAR  != 30)
if(VAR  == 40)
if(VAR  != 30)
if(VAR [VAR] <= 10)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= VAR)
if(VAR [VAR] >= 20)
if(VAR [VAR] != 10)
if(VAR [VAR] >= 40)
if(VAR [VAR] >= 30)
if(VAR  <= NULL)
if(VAR [VAR] >= 10)
if(VAR [VAR] != 30)
if(VAR [VAR] == 10)
if(VAR [VAR] >= 40)
if(VAR [VAR] == 10)
if(VAR [VAR] <= 30)
if(VAR [VAR] != VAR)
if(VAR [VAR] <= 20)
if(VAR [VAR] != 30)
if(VAR  >= VAR)
if(VAR  <= 20)
if(VAR  <= 20)
if(VAR  >= 40)
if(VAR [VAR] == 30)
if(VAR  <= 10)
if(VAR [VAR] != 10)
if(VAR  >= 10)
if(VAR  >= VAR)
if(VAR [VAR] == VAR)
if(VAR  >= 10)
if(VAR [VAR] == 40)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= 10)
if(VAR  <= 10)
if(VAR  != 30)
if(VAR [VAR] == 40)
if(VAR  <= VAR)
if(VAR  != 30)
if(VAR  == 20)
if(VAR  <= 20)
if(VAR [VAR] >= 30)
if(VAR [VAR] <= 40)
if(VAR  <= 20)
